spring.application.name=recipe-manager

spring.datasource.url=jdbc:h2:file:./data/recipe_manager;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.root=INFO
logging.level.com.yr.recipemanager=DEBUG
logging.file.name=app.log
